@url = http://localhost:2002/v1/client


###
POST {{url}}/predict
Content-Type: application/json

{
    "string" : "BBBBPPTPTPB"
}

###
POST http://103.116.105.147:2002/v1/client/predict
Content-Type: application/json

{
    "string" : "BBBBPPTPTPB"
}




###
POST http://192.168.40.110:2002/v1/client/forgotPassword/getVerifyCode
Content-Type: application/json

{
    "userEmail": "minhhy@gmail.com"
}


###
POST http://192.168.40.110:2002/v1/client/signup/getVerifyCode
Content-Type: application/json

{
    "userEmail": "minhhy001@gmail.com"
}


###
POST http://192.168.40.110:2002/v1/client/forgotPassword/getVerifyCode
Content-Type: application/json

{
    "userEmail": "minhhy@gmail.com"
}


###
POST http://192.168.40.110:2002/v1/client/signup/getVerifyCode
Content-Type: application/json

{
    "userEmail": "minhhy001@gmail.com"
}


###
POST http://192.168.40.110:2002/v1/client/signup
Content-Type: application/json

{
    "email": "minhhy001@gmail.com",
    "username": "Minh Hy",
    "password": "abc123",
    "verifyCode" : "844aef"
}



###
POST {{url}}/signup
Content-Type: application/json

{
    "username": "Minh Hy",
    "email": "minhhy@gmail.com",
    "password": "abc123"
}


###
POST {{url}}/signin
Content-Type: application/json

{
    "email": "minhhy@gmail.com",
    "password": "abc123"
}



###
POST {{url}}/logout
Content-Type: application/json
h-client-id: 64e78fa6cb798ff7c8bc4c14
athorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGU3OGZhNmNiNzk4ZmY3YzhiYzRjMTQiLCJlbWFpbCI6Im1pbmhoeUBnbWFpbC5jb20iLCJpYXQiOjE2OTI5MDA3NjUsImV4cCI6MTY5MzA3MzU2NX0.fTuGSn84joXwpQ33uJWy7vdK2S47ijzgQOyirj-S2fM



