@url = http://localhost:2002/v1/public

###
GET {{url}}/try/algorithm


###
POST {{url}}/try/tableResultString
Content-Type: application/json

{
    "string" : "0010101000011000110000010010011"
}


###
POST https://103.116.105.147:2002/v1/public/try/tableResultString
Content-Type: application/json

{
    "string" : "0010101000011000110000010010011"
}


###
POST http://192.168.40.110:2002/v1/public/try/tableResultString
Content-Type: application/json

{
    "string" : "001010100001100011000001001001101000111"
}



###
POST http://103.116.105.147:2002/v1/client/forgotPassword/getVerifyCode
Content-Type: application/json

{
    "userEmail": "minhhy@gmail.com"
}


###
POST http://103.116.105.147:2002/v1/client/signup/getVerifyCode
Content-Type: application/json

{
    "userEmail": "minhhy001@gmail.com"
}